/* Generated By:JJTree&JavaCC: Do not edit this line. CompiladorAulaConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompiladorAulaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ERAUMAVEZ = 5;
  /** RegularExpression Id. */
  int EVIVERAMFELIZESPARASEMPRE = 6;
  /** RegularExpression Id. */
  int PONTOEVIRGULA = 7;
  /** RegularExpression Id. */
  int VIRGULA = 8;
  /** RegularExpression Id. */
  int IGUAL = 9;
  /** RegularExpression Id. */
  int TIPOINTEIRO = 10;
  /** RegularExpression Id. */
  int TIPOBOOLEANO = 11;
  /** RegularExpression Id. */
  int TIPOCARACTER = 12;
  /** RegularExpression Id. */
  int FALSO = 13;
  /** RegularExpression Id. */
  int VERDADEIRO = 14;
  /** RegularExpression Id. */
  int ID = 15;
  /** RegularExpression Id. */
  int DECIMAL = 16;
  /** RegularExpression Id. */
  int DIGITO = 17;
  /** RegularExpression Id. */
  int LETRA = 18;
  /** RegularExpression Id. */
  int CARACTER = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"eraUmaVez\"",
    "\"eViveramFelizesParaSempre\"",
    "\";\"",
    "\",\"",
    "\"=\"",
    "\"inteiro\"",
    "\"booleano\"",
    "\"caracter\"",
    "\"falso\"",
    "\"verdadeiro\"",
    "<ID>",
    "<DECIMAL>",
    "<DIGITO>",
    "<LETRA>",
    "<CARACTER>",
  };

}
