/* Generated By:JavaCC: Do not edit this line. CompiladorAulaTreeConstants.java Version 5.0 */
package parser;

public interface CompiladorAulaTreeConstants
{
  public int JJTMAIN = 0;
  public int JJTERAUMAVEZ = 1;
  public int JJTEVIVERAMFELIZESPARASEMPRE = 2;
  public int JJTBLOCO = 3;
  public int JJTTIPODEDADOEDECALARACAODEVARIAVEIS = 4;
  public int JJTUMAOUMAISVARIAVEISCOMOUSEMATRIBUICAO = 5;
  public int JJTATRIBUICAOVALOR = 6;
  public int JJTDECLARACAODEOUTRAVARIAVEL = 7;
  public int JJTCONDICIONAL = 8;
  public int JJTREPETICAOENQUANTO = 9;
  public int JJTEXPRESSAOLOGICA = 10;
  public int JJTCONTINUAEXPRESSAOLOGICA = 11;
  public int JJTIDOUVALOR = 12;
  public int JJTOPERADORLOGICO = 13;
  public int JJTVALORBOOLEANO = 14;
  public int JJTVALOR = 15;
  public int JJTTIPODADO = 16;
  public int JJTPONTOEVIRGULA = 17;
  public int JJTVIRGULA = 18;
  public int JJTID = 19;
  public int JJTTIPOINTEIRO = 20;
  public int JJTTIPOBOOLEANO = 21;
  public int JJTTIPOCARACTER = 22;
  public int JJTSE = 23;
  public int JJTABREPARENTESES = 24;
  public int JJTFECHAPARENTESES = 25;
  public int JJTIGUAL = 26;
  public int JJTMAIORIGUAL = 27;
  public int JJTMENORIGUAL = 28;
  public int JJTDIFERENTE = 29;
  public int JJTE = 30;
  public int JJTOU = 31;
  public int JJTMAIOR = 32;
  public int JJTMENOR = 33;
  public int JJTRECEBE = 34;
  public int JJTVERDADEIRO = 35;
  public int JJTFALSO = 36;
  public int JJTABRECHAVES = 37;
  public int JJTFECHACHAVES = 38;
  public int JJTENQUANTO = 39;
  public int JJTLEIA = 40;
  public int JJTESCREVA = 41;
  public int JJTCARACTER = 42;
  public int JJTDECIMAL = 43;


  public String[] jjtNodeName = {
    "main",
    "eraUmaVez",
    "eViveramFelizesParaSempre",
    "bloco",
    "tipoDeDadoEDecalaracaoDeVariaveis",
    "umaOuMaisvariaveisComOuSemAtribuicao",
    "atribuicaoValor",
    "declaracaoDeOutraVariavel",
    "condicional",
    "repeticaoEnquanto",
    "expressaoLogica",
    "continuaExpressaoLogica",
    "idOuValor",
    "operadorLogico",
    "valorBooleano",
    "valor",
    "tipoDado",
    "pontoEVirgula",
    "virgula",
    "id",
    "tipoInteiro",
    "tipoBooleano",
    "tipoCaracter",
    "se",
    "abreParenteses",
    "fechaParenteses",
    "igual",
    "maiorIgual",
    "menorIgual",
    "diferente",
    "e",
    "ou",
    "maior",
    "menor",
    "recebe",
    "verdadeiro",
    "falso",
    "abreChaves",
    "fechaChaves",
    "enquanto",
    "leia",
    "escreva",
    "caracter",
    "decimal",
  };
}
/* JavaCC - OriginalChecksum=e32ef28e8949ffcd4024875a076805b5 (do not edit this line) */
