/* Generated By:JJTree&JavaCC: Do not edit this line. CompiladorAulaConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompiladorAulaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ERAUMAVEZ = 5;
  /** RegularExpression Id. */
  int EVIVERAMFELIZESPARASEMPRE = 6;
  /** RegularExpression Id. */
  int PONTOEVIRGULA = 7;
  /** RegularExpression Id. */
  int VIRGULA = 8;
  /** RegularExpression Id. */
  int IGUAL = 9;
  /** RegularExpression Id. */
  int MAIORIGUAL = 10;
  /** RegularExpression Id. */
  int MENORIGUAL = 11;
  /** RegularExpression Id. */
  int DIFERENTE = 12;
  /** RegularExpression Id. */
  int E = 13;
  /** RegularExpression Id. */
  int OU = 14;
  /** RegularExpression Id. */
  int MAIOR = 15;
  /** RegularExpression Id. */
  int MENOR = 16;
  /** RegularExpression Id. */
  int RECEBE = 17;
  /** RegularExpression Id. */
  int ABREPARENTESES = 18;
  /** RegularExpression Id. */
  int FECHAPARENTESES = 19;
  /** RegularExpression Id. */
  int ABRECHAVES = 20;
  /** RegularExpression Id. */
  int FECHACHAVES = 21;
  /** RegularExpression Id. */
  int TIPOINTEIRO = 22;
  /** RegularExpression Id. */
  int TIPOBOOLEANO = 23;
  /** RegularExpression Id. */
  int TIPOCARACTER = 24;
  /** RegularExpression Id. */
  int FALSO = 25;
  /** RegularExpression Id. */
  int VERDADEIRO = 26;
  /** RegularExpression Id. */
  int SE = 27;
  /** RegularExpression Id. */
  int ENQUANTO = 28;
  /** RegularExpression Id. */
  int LEIA = 29;
  /** RegularExpression Id. */
  int ESCREVA = 30;
  /** RegularExpression Id. */
  int ID = 31;
  /** RegularExpression Id. */
  int DECIMAL = 32;
  /** RegularExpression Id. */
  int DIGITO = 33;
  /** RegularExpression Id. */
  int LETRA = 34;
  /** RegularExpression Id. */
  int CARACTER = 35;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"eraUmaVez\"",
    "\"eViveramFelizesParaSempre\"",
    "\";\"",
    "\",\"",
    "\"==\"",
    "\">=\"",
    "\"<=\"",
    "\"!=\"",
    "\"&&\"",
    "\"||\"",
    "\" >\"",
    "\"< \"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"inteiro\"",
    "\"booleano\"",
    "\"caracter\"",
    "\"falso\"",
    "\"verdadeiro\"",
    "\"se\"",
    "\"enquanto\"",
    "\"leia\"",
    "\"escreva\"",
    "<ID>",
    "<DECIMAL>",
    "<DIGITO>",
    "<LETRA>",
    "<CARACTER>",
  };

}
