/* Generated By:JavaCC: Do not edit this line. CompiladorAulaTreeConstants.java Version 5.0 */
package parser;

public interface CompiladorAulaTreeConstants
{
  public int JJTMAIN = 0;
  public int JJTERAUMAVEZ = 1;
  public int JJTEVIVERAMFELIZESPARASEMPRE = 2;
  public int JJTBLOCO = 3;
  public int JJTTIPODEDADOEDECALARACAODEVARIAVEIS = 4;
  public int JJTUMAOUMAISVARIAVEISCOMOUSEMATRIBUICAO = 5;
  public int JJTATRIBUICAOVALOR = 6;
  public int JJTDECLARACAODEOUTRAVARIAVEL = 7;
  public int JJTCONDICIONAL = 8;
  public int JJTREPETICAOENQUANTO = 9;
  public int JJTREPETICAOFACAENQUANTO = 10;
  public int JJTEXPRESSAOLOGICA = 11;
  public int JJTCONTINUAEXPRESSAOLOGICA = 12;
  public int JJTOPERADORLOGICO = 13;
  public int JJTOPERACAOMATEMATICA = 14;
  public int JJTCONTINUAOPERACAOMATEMATICA = 15;
  public int JJTIDOUDECIMAL = 16;
  public int JJTOPERADORMATEMATICO = 17;
  public int JJTLEITURA = 18;
  public int JJTESCRITA = 19;
  public int JJTVALORBOOLEANO = 20;
  public int JJTIDOUVALOR = 21;
  public int JJTVALOR = 22;
  public int JJTTIPODADO = 23;
  public int JJTPONTOEVIRGULA = 24;
  public int JJTVIRGULA = 25;
  public int JJTID = 26;
  public int JJTTIPOINTEIRO = 27;
  public int JJTTIPOBOOLEANO = 28;
  public int JJTTIPOCARACTER = 29;
  public int JJTSE = 30;
  public int JJTABREPARENTESES = 31;
  public int JJTFECHAPARENTESES = 32;
  public int JJTIGUAL = 33;
  public int JJTMAIORIGUAL = 34;
  public int JJTMENORIGUAL = 35;
  public int JJTDIFERENTE = 36;
  public int JJTE = 37;
  public int JJTOU = 38;
  public int JJTMAIOR = 39;
  public int JJTMENOR = 40;
  public int JJTRECEBE = 41;
  public int JJTVERDADEIRO = 42;
  public int JJTFALSO = 43;
  public int JJTABRECHAVES = 44;
  public int JJTFECHACHAVES = 45;
  public int JJTENQUANTO = 46;
  public int JJTLEIA = 47;
  public int JJTESCREVA = 48;
  public int JJTCARACTER = 49;
  public int JJTDECIMAL = 50;
  public int JJTSOMA = 51;
  public int JJTSUBTRACAO = 52;
  public int JJTMULTIPLICACAO = 53;
  public int JJTDIVISAO = 54;
  public int JJTFACA = 55;


  public String[] jjtNodeName = {
    "main",
    "eraUmaVez",
    "eViveramFelizesParaSempre",
    "bloco",
    "tipoDeDadoEDecalaracaoDeVariaveis",
    "umaOuMaisvariaveisComOuSemAtribuicao",
    "atribuicaoValor",
    "declaracaoDeOutraVariavel",
    "condicional",
    "repeticaoEnquanto",
    "repeticaoFacaEnquanto",
    "expressaoLogica",
    "continuaExpressaoLogica",
    "operadorLogico",
    "operacaoMatematica",
    "continuaOperacaoMatematica",
    "idOuDecimal",
    "operadorMatematico",
    "leitura",
    "escrita",
    "valorBooleano",
    "idOuValor",
    "valor",
    "tipoDado",
    "pontoEVirgula",
    "virgula",
    "id",
    "tipoInteiro",
    "tipoBooleano",
    "tipoCaracter",
    "se",
    "abreParenteses",
    "fechaParenteses",
    "igual",
    "maiorIgual",
    "menorIgual",
    "diferente",
    "e",
    "ou",
    "maior",
    "menor",
    "recebe",
    "verdadeiro",
    "falso",
    "abreChaves",
    "fechaChaves",
    "enquanto",
    "leia",
    "escreva",
    "caracter",
    "decimal",
    "soma",
    "subtracao",
    "multiplicacao",
    "divisao",
    "faca",
  };
}
/* JavaCC - OriginalChecksum=184116e1e7c0301291f4e033c36c0a7d (do not edit this line) */
